/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CardsImport } from './routes/cards'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const CardsIdLazyImport = createFileRoute('/cards/$id')()
const CardsIdModalLazyImport = createFileRoute('/cards/$id/modal')()

// Create/Update Routes

const CardsRoute = CardsImport.update({
  path: '/cards',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CardsIdLazyRoute = CardsIdLazyImport.update({
  path: '/cards/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cards_.$id.lazy').then((d) => d.Route))

const CardsIdModalLazyRoute = CardsIdModalLazyImport.update({
  path: '/$id/modal',
  getParentRoute: () => CardsRoute,
} as any).lazy(() =>
  import('./routes/cards.$id_.modal.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsImport
      parentRoute: typeof rootRoute
    }
    '/cards/$id': {
      id: '/cards/$id'
      path: '/cards/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof CardsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/cards/$id/modal': {
      id: '/cards/$id/modal'
      path: '/$id/modal'
      fullPath: '/cards/$id/modal'
      preLoaderRoute: typeof CardsIdModalLazyImport
      parentRoute: typeof CardsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CardsRoute: CardsRoute.addChildren({ CardsIdModalLazyRoute }),
  CardsIdLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cards",
        "/cards/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cards": {
      "filePath": "cards.tsx",
      "children": [
        "/cards/$id/modal"
      ]
    },
    "/cards/$id": {
      "filePath": "cards_.$id.lazy.tsx"
    },
    "/cards/$id/modal": {
      "filePath": "cards.$id_.modal.lazy.tsx",
      "parent": "/cards"
    }
  }
}
ROUTE_MANIFEST_END */
