/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const CardsIdLazyImport = createFileRoute('/cards/$id')()
const CardsIdModalLazyImport = createFileRoute('/cards/$id/modal')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CardsIdLazyRoute = CardsIdLazyImport.update({
  path: '/cards/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cards.$id.lazy').then((d) => d.Route))

const CardsIdModalLazyRoute = CardsIdModalLazyImport.update({
  path: '/cards/$id/modal',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cards_.$id.modal.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cards/$id': {
      id: '/cards/$id'
      path: '/cards/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof CardsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/cards/$id/modal': {
      id: '/cards/$id/modal'
      path: '/cards/$id/modal'
      fullPath: '/cards/$id/modal'
      preLoaderRoute: typeof CardsIdModalLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CardsIdLazyRoute,
  CardsIdModalLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cards/$id",
        "/cards/$id/modal"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cards/$id": {
      "filePath": "cards.$id.lazy.tsx"
    },
    "/cards/$id/modal": {
      "filePath": "cards_.$id.modal.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
